"use strict";
module.exports = {
  config: {
    updateChannel: "stable",
    fontSize: 18,
    fontFamily: "Fira Code",
    //   'Menlo, "DejaVu Sans Mono", Consolas, "Lucida Console", monospace',
    fontWeight: "normal",
    fontWeightBold: "bold",
    lineHeight: 1,
    letterSpacing: 0,
    cursorColor: "rgba(179, 98, 255, 0.8)",
    cursorAccentColor: "#000",
    cursorShape: "BLOCK",
    cursorBlink: false,
    foregroundColor: "#FFFFFF",
    backgroundColor: "#222244",
    selectionColor: "rgba(248,28,229,0.3)",
    borderColor: "#333",
    css: "",
    termCSS: "",
    workingDirectory: "",
    showHamburgerMenu: "",
    showWindowControls: "",
    padding: "12px 14px",
    colors: {
      black: "#000000",
      red: "#FF4D4D",
      green: "#3EFF3E",
      yellow: "#FFEB4D",
      blue: "#7A8FFF",
      magenta: "#FF80FF",
      cyan: "#6CFFFF",
      white: "#FFFFFF",
      lightBlack: "#8C8C8C",
      lightRed: "#FFB7B7",
      lightGreen: "#9DFF9D",
      lightYellow: "#FFFF9D",
      lightBlue: "#BAC4FF",
      lightMagenta: "#FFC9FF",
      lightCyan: "#C1FFFF",
      lightWhite: "#FFFFFF",
      limeGreen: "#00FF00",
      lightCoral: "#FF8484",
    },
    shell: "",
    shellArgs: ["--login"],
    env: {},
    bell: "SOUND",
    copyOnSelect: false,
    defaultSSHApp: true,
    quickEdit: false,
    macOptionSelectionMode: "vertical",
    webGLRenderer: true,
    webLinksActivationKey: "",
    disableLigatures: false,
    disableAutoUpdates: false,
    screenReaderMode: false,
    preserveCWD: true,
  },
  plugins: [],
  localPlugins: [],
  keymaps: {},
};
